# Generated by Django 5.0.2 on 2024-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_rename_img_produit_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
