# Generated by Django 5.0.2 on 2024-05-10 22:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_rename_total_commande_totalcde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='totalCde',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
