# Generated by Django 5.0.2 on 2024-05-11 01:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_rename_duree_garantie_produitc_duree_garantie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitc',
            old_name='duree_garantie',
            new_name='Duree_garantie',
        ),
        migrations.RenameField(
            model_name='produitnc',
            old_name='duree_garantie',
            new_name='Duree_garantie',
        ),
        migrations.AlterField(
            model_name='commande',
            name='totalCde',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
    ]
